name:          "Euclidean Geometry"
description:   "Course Page for UNI Math 3600"
email:         theron.hitchman@uni.edu

url:           "http://theronhitchman.github.io/euclidean-geometry"

paginate:      10

markdown:      kramdown
permalink:     pretty
highlighter:   pygments
